// VerticalCard 목업 데이터
export const MockUpCardData = [
  {
    id: 1,
    onSell: true,
    productName: "진한 맛! 태양이 타이백 감귤",
    description: "부가설명 부가설명",
    price: 42000,
    cart: true,
    label: "normal",
  },
  {
    id: 2,
    onSell: false,
    productName: "진한 맛! 태양이 타이백 감귤",
    description: "부가설명 부가설명",
    price: 39000,
    cart: false,
    label: "moonan",
  },
  {
    id: 3,
    onSell: true,
    productName: "진한 맛! 태양이 타이백 감귤",
    description: "부가설명 부가설명",
    price: 42000,
    cart: false,
    label: "moonan",
  },
  {
    id: 4,
    onSell: false,
    productName: "진한 맛! 태양이 타이백 감귤",
    description: "부가설명 부가설명",
    price: 40000,
    cart: true,
    label: "normal",
  },
  {
    id: 5,
    onSell: true,
    productName: "진한 맛! 태양이 타이백 감귤",
    description: "부가설명 부가설명",
    price: 40000,
    cart: true,
    label: "normal",
  },
  {
    id: 6,
    onSell: true,
    productName: "진한 맛! 태양이 타이백 감귤",
    description: "부가설명 부가설명",
    price: 40000,
    cart: true,
    label: "moonan",
  },
  {
    id: 7,
    onSell: false,
    productName: "진한 맛! 태양이 타이백 감귤",
    description: "부가설명 부가설명",
    price: 40000,
    cart: true,
    label: "normal",
  },
  {
    id: 8,
    onSell: true,
    productName: "진한 맛! 태양이 타이백 감귤",
    description: "부가설명 부가설명",
    price: 40000,
    cart: true,
    label: "normal",
  },
];
